version: '3'

services:

  backend:
    build: ./backend
    container_name: 'backend'
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file: 
      - .env
    restart: always

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - backend

  frontend:
    stdin_open: true
    image: node:13.2.0
    container_name: 'client'
    command: ["/src/client/dev-nuxt.sh"]
    volumes:
      - .:/src
      - node_modules:/src/client/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  app:
  node_modules:

